config/routes.rb
Rails.application.routes.draw do
  
  root "fichas#index"
  resources :fichas
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ficha.rb
class Ficha < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fichas_controller.rb
class FichasController < ApplicationController
  before_action :set_ficha, only: [:show, :edit, :update, :destroy]

  # GET /fichas
  # GET /fichas.json
  def index
    @fichas = Ficha.all
  end

  # GET /fichas/1
  # GET /fichas/1.json
  def show
  end

  # GET /fichas/new
  def new
    @ficha = Ficha.new
  end

  # GET /fichas/1/edit
  def edit
  end

  # POST /fichas
  # POST /fichas.json
  def create
    @ficha = Ficha.new(ficha_params)

    respond_to do |format|
      if @ficha.save
        format.html { redirect_to root_url, notice: 'Ficha was successfully created.' }
        format.json { render :show, status: :created, location: @ficha }
      else
        format.html { render :new }
        format.json { render json: @ficha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fichas/1
  # PATCH/PUT /fichas/1.json
  def update
    respond_to do |format|
      if @ficha.update(ficha_params)
        format.html { redirect_to root_url, notice: 'Ficha was successfully updated.' }
        format.json { render :show, status: :ok, location: @ficha }
      else
        format.html { render :edit }
        format.json { render json: @ficha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fichas/1
  # DELETE /fichas/1.json
  def destroy
    @ficha.destroy
    respond_to do |format|
      format.html { redirect_to fichas_url, notice: 'Ficha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ficha
      @ficha = Ficha.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ficha_params
      params.require(:ficha).permit(:titulo, :fecha, :descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/views/fichas/_form.html.erb
<%= form_with(model: ficha, local: true) do |form| %>
  <% if ficha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ficha.errors.count, "error") %> prohibited this ficha from being saved:</h2>

      <ul>
      <% ficha.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fichas/edit.html.erb
<h1>Editing Ficha</h1>

<%= render 'form', ficha: @ficha %>

<%= link_to 'Show', @ficha %> |
<%= link_to 'Back', fichas_path %>

app/views/fichas/index.html.erb
<html>
<head>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/v4-shims.css">
</head>


<body>
<div class="new-list">
  <%= link_to new_ficha_path do %>
  <i class="fas fa-plus-square fa-3x" aria-hidden="true"></i>
  <%end%>
</div>

  <div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-2 col-sm-8">
      <ul class="tecno-list">
         
    <% @fichas.each do |ficha| %>
              <li>
                <time datetime="2014-07-20">
                  <span class="day"> <%= ficha.fecha.mday %> </span>
                  <span class="month"><%= ficha.fecha.strftime("%B").first(3) %></span>
                  <span class="year"><%= ficha.fecha.year %></span>
                  <span class="time">ALL DAY</span>
                </time>
                <div class="info">
                  <h2 class="title"><%= ficha.titulo %></h2>
                </div>
                  <div class="social">
                  <ul>
                    <li class="eye" style="width:33%;">
                     
                     <%= link_to ficha do %>
                      <span class="fa fa-eye"></span>
                      <%end%>
                    </li>

                    <li class="pencil" style="width:34%;">
                      
                      <%= link_to edit_ficha_path(ficha) do %>
                        <span class="fa fa-pencil-square-o"></span>
                      <%end%>
                    </li>
                    <li class="times" style="width:33%;">
                    <%= link_to ficha, method: :delete, data: { confirm: 'Estas seguro?' } do%>
                      <span class="fa fa-times"></span>
                    <%end%>
                    </li>
                  </ul>
                </div>
              </li>
        <% end %>

      
        

      </ul>
    </div>
  </div>
</div>
</body>
</html>

app/views/fichas/new.html.erb
<h1>Nueva Nota</h1>

<%= render 'form', ficha: @ficha %>

<%= link_to 'Back', fichas_path %>

app/views/fichas/show.html.erb
<!--<p id="notice"><%= notice %></p>-->


<div class="card text-center">
  <div class="card-header bg-secondary">
    <%= @ficha.titulo %>
  </div>
  <div class="card-body">
    
    <p class="card-text"><%= @ficha.descripcion %></p>

    <a href="<%= edit_ficha_path(@ficha) %>" class="btn btn-light btn-sm">Editar</a>
    <a href="<%= fichas_path%>" class="btn btn-light btn-sm" TARGET="_top">Volver</a>
    
    <!-- TARGET="_top" para recargar la pagina al volver-->

        
  </div>
  <div class="card-footer text-muted">
    <%= @ficha.fecha %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Required meta tags -->
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


  </head>

  <body>
    <%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  
  </body>
</html>